config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'people#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, :last_name, :email, :birthday, presence: true
  validates :first_name, :last_name, :job, length: { maximum: 75 }
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i 
  validates :job, presence: false
  validate :birthday_cannot_be_in_the_past

  def birthday_cannot_be_in_the_past
    errors.add(:birthday, "has to be in the past") if
      !birthday.blank? and birthday > Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :find_person, only: [:show, :edit, :update, :destroy]
  before_filter :find_genders, only: [:new, :edit]

  def index
    @people = Person.order(:first_name)
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      send_email(@person, 'added')
      redirect_to person_path(@person)
    else
      flash.now[:error] = @person.errors.messages
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @person.update(person_params)
      redirect_to @person
    else
      flash.now[:error] = @person.errors.messages
      render 'edit'
    end
  end

  def destroy
    @person.delete
    send_email(@person, 'deleted')
    redirect_to people_path
  end

  private

  def find_genders
    @genders = ['Male', 'Female', 'Other']
  end

  def send_email(person, action)
    person_hash = { 'first_name' => @person.first_name,
                    'last_name' => @person.last_name }
    SendEmailJob.perform_later(person_hash, action)
  end

  def find_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :email, :job,
                                   :gender, :birthday, :picture, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  def person_age(birthday)
    dob = birthday
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManagePeopleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_flash_messages.html.erb
<% if flash[:error] %>
    <div class='alert'>
			<a href='#' class='close'>&times;</a>
      <b>We're sorry, we couldn't save the info:</b>
      <% flash[:error].each do |attr, messages| %>
        <% messages.each do | msg | %>
          <div><%= attr.to_s.humanize + ' ' + msg.capitalize %></div>
        <% end %>
      <% end %>
    </div>
<% end %>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <form>
    <%= render 'flash_messages' %>
    <div class="form-group">
      <%= f.label 'First name' %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Last name' %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Email' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Job' %>
      <%= f.text_field :job, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Gender' %>
      <%= f.select :gender, options_for_select(@genders.collect {|g|[g,g]}, selected: @person.gender), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Bio' %>
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Birthday' %>
      <%= f.date_field :birthday, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Picture URL' %>
      <%= f.text_field :picture, class: 'form-control' %>
    </div>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </form>
<% end %>

app/views/people/edit.html.erb
<div class="content-fluid col-sm-6">
  <h1><%= "Edit #{@person.first_name} #{@person.last_name} information" %></h1>
  <hr>
  <%= render 'form' %>
  <div>
    <%= link_to 'Cancel', person_path(@person), class: 'btn btn-default' %>
  </div>
</div>
<br><br>

app/views/people/index.html.erb
<div class="container-fluid col-sm-6">
  <h1>Listing people</h1>
  <br>
  <%= link_to 'Add a new person', new_person_path, class: 'btn btn-primary' %>
  <br><br>
  <div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>First name & Last name</th>
        <th>Email</th>
        <th>Age</th>
        <th>Delete</th>
      </tr>
    </thead>
    <% @people.each do |person| %>
      <tbody>
        <tr>
          <td><%= link_to "#{person.first_name} #{person.last_name}", person %></td>
          <td><%= person.email %></td>
          <td><%= person_age(person.birthday) %></td>
          <td><%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  </div>
</div>
<br><br>

app/views/people/new.html.erb
<div class="content-fluid col-sm-6">
  <h1>Add a new person</h1>
  <hr>
  <%= render 'form' %>
  <%= link_to 'Cancel', people_path, class: 'btn btn-default' %>
</div>
<br><br>

app/views/people/show.html.erb
<div class="container-fluid col-sm-6">
  <h1><%= "#{@person.first_name} #{@person.last_name}'s profile" %></h1>
  <br><br>
  <div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th class="text-nowrap" scope="row">First name</th>
      <td colspan="3"><%= @person.first_name %></td>
    </tr>
    <tr>
      <th class="text-nowrap" scope="row">Last name</th>
      <td colspan="3"><%= @person.last_name %></td>
    </tr>
    <tr>
      <th class="text-nowrap" scope="row">Email</th>
      <td colspan="3"><%= @person.email %></td>
    </tr>
    <tr>
      <th class="text-nowrap" scope="row">Job</th>
      <td colspan="3"><%= @person.job %></td>
    </tr>
    <tr>
      <th class="text-nowrap" scope="row">Gender</th>
      <td colspan="3"><%= @person.gender %></td>
    </tr>
    <tr>
      <th class="text-nowrap" scope="row">Birthday (Age)</th>
      <td colspan="3"><%= "#{@person.birthday} (#{person_age(@person.birthday)})" %></td>
    </tr>
    <tr>
      <th class="text-nowrap" scope="row">Bio</th>
      <td colspan="3"><%= @person.bio %></td>
    </tr>
  </table>
  </div>
  <div> 
    <p>
      <%= link_to 'Edit', edit_person_path(@person), class: 'btn btn-primary' %>
      <%= link_to 'Cancel', people_path, class: 'btn btn-default' %>
      <%= link_to 'Delete', @person, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</div>
<br><br>